yourssu/soongpt-backend

src/main/kotlin/com/yourssu/soongpt/common/config/SwaggerConfig.kt
src/main/kotlin/com/yourssu/soongpt/common/config/WebConfig.kt

- swagger server url이 http으로 설정되어 발생하는 cors 문제, 상대 경로(https)로 변경함으로써 해결하였습니다.

fix: cors 에러 해결

---

src/main/kotlin/com/yourssu/soongpt/common/business/initialization/CollegesAndDepartmentsInitializer.kt
src/main/kotlin/com/yourssu/soongpt/domain/course/application/CourseController.kt
src/main/kotlin/com/yourssu/soongpt/domain/course/application/dto/MajorCoreCourseRequest.kt
src/main/kotlin/com/yourssu/soongpt/domain/course/business/CourseService.kt
src/main/kotlin/com/yourssu/soongpt/domain/course/business/dto/CourseResponse.kt
src/main/kotlin/com/yourssu/soongpt/domain/course/implement/Classification.kt
src/main/kotlin/com/yourssu/soongpt/domain/course/implement/CourseReader.kt
src/main/kotlin/com/yourssu/soongpt/domain/courseTime/business/dto/CourseTimeResponse.kt
src/main/kotlin/com/yourssu/soongpt/domain/courseTime/implement/Week.kt
src/main/kotlin/com/yourssu/soongpt/domain/departmentGrade/implement/DepartmentGradeRepository.kt
src/main/kotlin/com/yourssu/soongpt/domain/departmentGrade/implement/DepartmentGradeWriter.kt
src/main/kotlin/com/yourssu/soongpt/domain/departmentGrade/storage/DepartmentGradeRepositoryImpl.kt
src/main/kotlin/com/yourssu/soongpt/domain/target/implement/TargetReader.kt
src/main/resources/http/course.http
src/test/kotlin/com/yourssu/soongpt/common/support/fixture/CourseFixture.kt
src/test/kotlin/com/yourssu/soongpt/common/support/fixture/CourseTimeFixture.kt
src/test/kotlin/com/yourssu/soongpt/domain/course/storage/business/CourseServiceTest.kt
src/test/kotlin/com/yourssu/soongpt/domain/courseTime/storage/CourseTimeRepositoryImplTest.kt

Closes #11, closes #12, closes #18
- 테스트 코드 구현했고 테스트 만드는 과정에서 빼먹은거 발견해서 초기화 코드도 바꿨어요.

Feat: 전공 필수 과목 조회 요청 API 구현

---

build.gradle.kts
src/main/kotlin/com/yourssu/soongpt/SoongptApplication.kt
src/main/kotlin/com/yourssu/soongpt/common/config/SlackProperties.kt
src/main/kotlin/com/yourssu/soongpt/common/infrastructure/SlackAlarmFeignClient.kt
src/main/kotlin/com/yourssu/soongpt/common/infrastructure/SlackAlarmProducer.kt
src/main/kotlin/com/yourssu/soongpt/common/infrastructure/dto/SlackAlarmRequest.kt
src/main/resources/application-local.yml
src/test/kotlin/com/yourssu/soongpt/common/infrastructure/SlackAlarmProducerTest.kt
src/test/resources/application-test.yml

Closes #15
- 실제 서버 accessToken, channel Id는 dev/prod 서버 yaml 파일에서 환경변수로 관리하려고 합니다.

Feat: 슬랙 알림 봇 구현 ✨ 

---

src/main/kotlin/com/yourssu/soongpt/domain/rating/application/RatingController.kt
src/main/kotlin/com/yourssu/soongpt/domain/rating/application/dto/RatingCreatedRequest.kt
src/main/kotlin/com/yourssu/soongpt/domain/rating/application/dto/RatingFoundRequest.kt
src/main/kotlin/com/yourssu/soongpt/domain/rating/business/RatingCreatedCommand.kt
src/main/kotlin/com/yourssu/soongpt/domain/rating/business/RatingFoundCommand.kt
src/main/kotlin/com/yourssu/soongpt/domain/rating/business/RatingService.kt
src/main/kotlin/com/yourssu/soongpt/domain/rating/business/dto/RatingResponse.kt
src/main/kotlin/com/yourssu/soongpt/domain/rating/implement/Rating.kt
src/main/kotlin/com/yourssu/soongpt/domain/rating/implement/RatingReader.kt
src/main/kotlin/com/yourssu/soongpt/domain/rating/implement/RatingRepository.kt
src/main/kotlin/com/yourssu/soongpt/domain/rating/implement/RatingWriter.kt
src/main/kotlin/com/yourssu/soongpt/domain/rating/implement/exception/RatingNotFoundByCourseNameException.kt
src/main/kotlin/com/yourssu/soongpt/domain/rating/storage/RatingEntity.kt
src/main/kotlin/com/yourssu/soongpt/domain/rating/storage/RatingRepositoryImpl.kt

Feat: 평점 저장, 조회 기능 구현 ✨

---

src/main/kotlin/com/yourssu/soongpt/domain/course/application/CourseController.kt
src/main/kotlin/com/yourssu/soongpt/domain/course/business/CourseParser.kt
src/main/kotlin/com/yourssu/soongpt/domain/course/implement/Classification.kt
src/main/kotlin/com/yourssu/soongpt/domain/courseTime/implement/Week.kt

- 교수 데이터가 빈 문자열인 경우 예외 케이스로 처리
- Classification, Week > 일치하는 이름을 갖는 원소 반환 함수 `fromName()` 생성

feat: 교수 데이터가 빈 문자열인 경우 예외 케이스로 처리

---

.github/workflows/dev.yml
.gitignore
script/run.sh
src/main/resources/application-prod.yml

chore: CI/CD 전략 변경

---

.github/workflows/claude.yml
.github/workflows/prod.yml
CLAUDE.md

chore: claude code 코드 리뷰

---

src/main/kotlin/com/yourssu/soongpt/domain/contact/application/ContactController.kt
src/main/kotlin/com/yourssu/soongpt/domain/contact/application/dto/ContactRequest.kt
src/main/kotlin/com/yourssu/soongpt/domain/contact/business/ContactService.kt
src/main/kotlin/com/yourssu/soongpt/domain/contact/implement/Contact.kt
src/main/kotlin/com/yourssu/soongpt/domain/contact/implement/ContactRepository.kt
src/main/kotlin/com/yourssu/soongpt/domain/contact/storage/ContactEntity.kt
src/main/kotlin/com/yourssu/soongpt/domain/contact/storage/ContactRepositoryImpl.kt
src/main/resources/api/contact/create_contact.md

feat: 사전예약용 연락처 저장 API

---

src/main/kotlin/com/yourssu/soongpt/domain/timetable/business/TimetableService.kt
src/main/kotlin/com/yourssu/soongpt/domain/timetable/business/dto/TimetableCourseResponse.kt
src/main/kotlin/com/yourssu/soongpt/domain/timetable/business/dto/TimetableResponse.kt
src/main/kotlin/com/yourssu/soongpt/domain/timetable/implement/Tag.kt
src/main/kotlin/com/yourssu/soongpt/domain/timetable/implement/Timetable.kt
src/main/kotlin/com/yourssu/soongpt/domain/timetable/implement/TimetableCourse.kt
src/main/kotlin/com/yourssu/soongpt/domain/timetable/implement/TimetableCourseReader.kt
src/main/kotlin/com/yourssu/soongpt/domain/timetable/implement/TimetableCourseRepository.kt
src/main/kotlin/com/yourssu/soongpt/domain/timetable/implement/TimetableCourseWriter.kt
src/main/kotlin/com/yourssu/soongpt/domain/timetable/implement/TimetableGenerator.kt
src/main/kotlin/com/yourssu/soongpt/domain/timetable/implement/TimetableReader.kt
src/main/kotlin/com/yourssu/soongpt/domain/timetable/implement/TimetableRepository.kt
src/main/kotlin/com/yourssu/soongpt/domain/timetable/implement/TimetableWriter.kt
src/main/kotlin/com/yourssu/soongpt/domain/timetable/storage/TimeTableRepositoryImpl.kt
src/main/kotlin/com/yourssu/soongpt/domain/timetable/storage/TimetableCourseEntity.kt
src/main/kotlin/com/yourssu/soongpt/domain/timetable/storage/TimetableCourseRepositoryImpl.kt
src/main/kotlin/com/yourssu/soongpt/domain/timetable/storage/TimetableEntity.kt
src/main/kotlin/com/yourssu/soongpt/domain/timetable/storage/exception/TimetableNotFoundException.kt

feat: 시간표 도메인 설정

---

src/main/kotlin/com/yourssu/soongpt/domain/course/business/CourseService.kt
src/main/kotlin/com/yourssu/soongpt/domain/course/implement/CourseReader.kt
src/main/kotlin/com/yourssu/soongpt/domain/course/implement/CourseRepository.kt
src/main/kotlin/com/yourssu/soongpt/domain/course/storage/CourseRepositoryImpl.kt
src/main/kotlin/com/yourssu/soongpt/domain/target/implement/TargetReader.kt
src/main/kotlin/com/yourssu/soongpt/domain/target/implement/TargetRepository.kt
src/main/kotlin/com/yourssu/soongpt/domain/target/storage/TargetEntity.kt
src/main/kotlin/com/yourssu/soongpt/domain/target/storage/TargetRepositoryImpl.kt

[#87]; feat: 전필, 전선, 교필 과목 조회 API 구현

---

src/main/kotlin/com/yourssu/soongpt/domain/course/business/CourseService.kt
src/main/kotlin/com/yourssu/soongpt/domain/course/implement/CourseReader.kt
src/main/kotlin/com/yourssu/soongpt/domain/course/implement/CourseRepository.kt
src/main/kotlin/com/yourssu/soongpt/domain/course/storage/CourseEntity.kt
src/main/kotlin/com/yourssu/soongpt/domain/course/storage/CourseRepositoryImpl.kt
src/main/kotlin/com/yourssu/soongpt/domain/target/implement/TargetReader.kt
src/main/kotlin/com/yourssu/soongpt/domain/target/implement/TargetRepository.kt
src/main/kotlin/com/yourssu/soongpt/domain/target/storage/TargetEntity.kt
src/main/kotlin/com/yourssu/soongpt/domain/target/storage/TargetRepositoryImpl.kt

Closes #90
- @Moongss 이슈에서 사용 가능한 메서드 참고해 시간표 생성 에서 사용하면 됩니다. 질문 주세요.

[#90]; feat: 모든 분반에 대한 과목 조회 메서드

---

src/main/kotlin/com/yourssu/soongpt/domain/course/implement/CourseReader.kt
src/main/kotlin/com/yourssu/soongpt/domain/course/implement/CourseRepository.kt
src/main/kotlin/com/yourssu/soongpt/domain/course/implement/dto/GroupedCoursesByCategoryDto.kt
src/main/kotlin/com/yourssu/soongpt/domain/course/storage/CourseRepositoryImpl.kt
src/main/kotlin/com/yourssu/soongpt/domain/target/implement/TargetRepository.kt
src/main/kotlin/com/yourssu/soongpt/domain/target/storage/TargetRepositoryImpl.kt
src/main/kotlin/com/yourssu/soongpt/domain/timetable/implement/TimetableCourseReader.kt

[#96]; feat: Course 카테고리 별 그룹 메서드 구현

---

src/main/kotlin/com/yourssu/soongpt/domain/timetable/implement/CourseCandidateFactory.kt
src/main/kotlin/com/yourssu/soongpt/domain/timetable/implement/TimetableGenerator.kt
src/main/kotlin/com/yourssu/soongpt/domain/timetable/implement/dto/CompressTime.kt
src/main/kotlin/com/yourssu/soongpt/domain/timetable/implement/dto/CompressTimes.kt
src/main/kotlin/com/yourssu/soongpt/domain/timetable/implement/dto/CourseCandidate.kt
src/main/kotlin/com/yourssu/soongpt/domain/timetable/implement/dto/CourseCandidates.kt
src/main/kotlin/com/yourssu/soongpt/domain/timetable/implement/dto/TimetableCandidate.kt

Closes #92
- TimeTableGenerator 내부 메서드로 getAll~() 네이밍을 썼는데 어떤 역할을 하는지 제대로 드러내지 않는 느낌입니다.

feat: CourseReader를 통한 시간표 생성 전처리

---

src/main/kotlin/com/yourssu/soongpt/common/handler/GlobalControllerAdvice.kt
src/main/kotlin/com/yourssu/soongpt/domain/course/application/CourseController.kt
src/main/kotlin/com/yourssu/soongpt/domain/course/application/dto/GetCoursesByCodeRequest.kt
src/main/kotlin/com/yourssu/soongpt/domain/course/business/CourseService.kt
src/main/kotlin/com/yourssu/soongpt/domain/course/business/dto/CourseDetailResponse.kt
src/main/kotlin/com/yourssu/soongpt/domain/course/implement/CourseReader.kt

[#101]; feat: getCoursesByCode 구현

---

src/main/kotlin/com/yourssu/soongpt/domain/course/application/dto/SearchCoursesRequest.kt
src/main/kotlin/com/yourssu/soongpt/domain/course/implement/CourseReader.kt
src/main/kotlin/com/yourssu/soongpt/domain/course/implement/CourseRepository.kt
src/main/kotlin/com/yourssu/soongpt/domain/course/storage/CourseRepositoryImpl.kt
src/main/resources/api/course/search_course.md

[#106]; feat: 검색 제약사항 변경

---

src/main/kotlin/com/yourssu/soongpt/domain/timetable/implement/CourseCandidateFactory.kt
src/main/kotlin/com/yourssu/soongpt/domain/timetable/implement/TimetableGenerator.kt
src/main/kotlin/com/yourssu/soongpt/domain/timetable/implement/dto/CompressTime.kt
src/main/kotlin/com/yourssu/soongpt/domain/timetable/implement/dto/TimetableCandidate.kt
src/main/kotlin/com/yourssu/soongpt/domain/timetable/implement/timeslot/TimeSlotConstants.kt

사용자 선택 과목 한정 TimetableCandidate 생성

---

src/main/kotlin/com/yourssu/soongpt/domain/timetable/application/dto/TimetableCreatedRequest.kt
src/main/kotlin/com/yourssu/soongpt/domain/timetable/business/dto/TimetableCreatedCommand.kt
src/main/resources/api/timetable/create_timetable.md
src/main/resources/http/timetable.http

Closes #109 
- 디자인 변경에 따른 추천받을 교양 학점과 같이 넘길 "사용자 선호 교양 분야" 필드 추가

시간표 생성 API 필드 추가

---

src/main/kotlin/com/yourssu/soongpt/domain/target/storage/TargetRepositoryImpl.kt

[#115]; fix: casting to longValue before equal operating

---

src/main/kotlin/com/yourssu/soongpt/domain/course/storage/CourseRepositoryImpl.kt
src/main/resources/api/course/search_course.md

[#128]; feat: 과목 검색 대상을 이름, 교수만 찾도록 변경한다.

---

script/soongpt_handler.py
src/main/kotlin/com/yourssu/soongpt/common/infrastructure/dto/TimetableCreatedAlarmRequest.kt
src/main/kotlin/com/yourssu/soongpt/common/infrastructure/notification/Notification.kt
src/main/kotlin/com/yourssu/soongpt/domain/timetable/application/TimetableController.kt
src/main/kotlin/com/yourssu/soongpt/domain/timetable/business/TimetableService.kt
src/main/kotlin/com/yourssu/soongpt/domain/timetable/implement/TimetableReader.kt
src/main/kotlin/com/yourssu/soongpt/domain/timetable/implement/TimetableRepository.kt
src/main/kotlin/com/yourssu/soongpt/domain/timetable/storage/TimeTableRepositoryImpl.kt

feat: 시간표 생성시 슬랙 알람 메시지 전송 기능 구현

---

src/main/kotlin/com/yourssu/soongpt/domain/timetable/implement/TimetableGenerator.kt

이때 같은 시간표 형태여도, 내부 과목이 다를 수 있어서 timeSlot과 codes를 확인 후 중복 처리
Closes #134
-

[#134]; feat: 같은 시간표, 다른 태그의 경우 중복 시간표 제거

---

src/main/kotlin/com/yourssu/soongpt/domain/timetable/implement/TimetableGenerator.kt

- codeToMap을 만들때 같은 별점이어도 strict increasing하게 rank를 부여해서 발생한 문제였습니다.
Closes #138
-

[#138]; fix: 교선을 랜덤으로 추천해주지 않는 문제 해결

---

.dockerignore
.github/workflows/docker.yml
Dockerfile
script/requirements.txt

[#148]; chore: docker image settings
